name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - '**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          # Install Wrangler CLI
          npm install -g wrangler
          
          # Update wrangler.toml with secrets
          sed -i "s/\$ACCOUNT_ID/$ACCOUNT_ID/" wrangler.toml
          sed -i "s/your-database-id/$DATABASE_ID/" wrangler.toml
          sed -i "s/\"\"/'$CLIENT_ID'/" wrangler.toml
          sed -i "s/\"\"/'$TENANT_ID'/" wrangler.toml
          sed -i "s/\"\"/'$CLIENT_SECRET'/" wrangler.toml
          
          # Deploy using Wrangler CLI
          wrangler deploy
